name: Run solution unit tests
on:
  pull_request:
    branches:
      - 'solution/[0-9][0-9][0-9][0-9]/[0-9][0-9]'
      - 'improvement/[0-9][0-9][0-9][0-9]/[0-9][0-9]'
  push:
    branches: 
      - master
      - 'solution/[0-9][0-9][0-9][0-9]/[0-9][0-9]'
      - 'improvement/[0-9][0-9][0-9][0-9]/[0-9][0-9]'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository to actions pipeline
        uses: actions/checkout@v3

      - name: Provising required version of Golang
        uses: actions/setup-go@v3
        with:
            go-version: 1.23.4 

      - name: Running solution tests using `Makefile`
        run: make test
